# Generated by Django 4.0.4 on 2022-06-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sweet',
            old_name='date_created',
            new_name='timestamp',
        ),
    ]
